### ISSUE TITLE
pip install --user error

### ISSUE THREAD

**Issue by dmalan** [cs50/baseimage#31]
```
pyenv: cannot rehash: /opt/pyenv/shims isn't writable
```

**Comment by kzidane** [comment]
Just ran into this. It's because `/opt/pyenv` is obviously owned by `root`. Googling if it's recommended to `chmod -R a+w /opt/pyenv/shims`.

**Comment by dmalan** [comment]
Definitely shouldn't let any user write to `/opt/pyenv/shims`. Must be another way?

**Comment by kzidane** [comment]
The other way involves disabling automatic rehashing. If you wanna take that approach, we might need to write a wrapper function for `pip` that disables rehashing when `--user` is passed.

**Comment by kzidane** [comment]
Alternatively, we could disable rehashing globally and if users want to `sudo pip3 install` they should do `sudo pyenv rehash` afterwards.

**Comment by dmalan** [comment]
Hm, this seems weird. Surely there must be a way to install some packages globally with `pip3 install` and locally with `pip3 install --user` without such messiness, no?

**Comment by kzidane** [comment]
It's because we're using `pyenv`. By default when we run `pip3 install ...`, the package is installed somewhere under `$PYENV_ROOT` which happens to be `/opt/pyenv` in `cs50/baseimage` and the shims are therefore installed under `/opt/pyenv/shims`. After the installation is done, `pyenv` runs `pyenv rehash` to update its shims per https://github.com/pyenv/pyenv#understanding-shims (even though that shouldn't be needed when using `--user`). For all what `pyenv` cares, `$PYENV_ROOT/shims` should be writable by the current user. In fact, the default `$PYENV_ROOT` in its installation script is `~/.pyenv`, but of course we don't want that to be in the user's home folder. So the solutions are:
* disabling rehashing globally and do it manually afterwards
* writing a wrapper function that disables rehashing temporarily when user `--user`
* changing `$PYENV_ROOT` to be somewhere writable by the current user
* not use `pyenv`

**Comment by kzidane** [comment]
@dmalan, how would you like to handle this?

**Comment by ashenm** [comment]
Hm, how about adding a supplementary group with writable permissions to `/opt/pyenv/shims` and make `ubuntu` a member?

**Comment by dmalan** [comment]
Sorry for the belated reply, @kzidane, @ashenm! Ended up removing `pyenv` in favor of Python's own installer, which simplifies!
